version: "3.9"
services:
  api:
    build: .
    container_name: sac_api
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --proxy-headers --log-level info
    env_file: .env
    depends_on: [db, redis]
    working_dir: /code
    volumes: [".:/code"]
    ports: ["8010:8000"]
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: sac_redis
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: sac_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes: [ "sac_pg:/var/lib/postgresql/data" ]
    restart: unless-stopped

volumes:
  sac_pg:
